# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/io_plan.xdc

# IP: ip/mapram1/mapram1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mapram1 || ORIG_REF_NAME==mapram1} -quiet] -quiet
